{% set name = "mkdocs-git-revision-date-localized-plugin" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38517e2084229da1a1b9460e846c2748d238c2d79efd405d1b9174a87bd81d79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mkdocs >=1.0
    - gitpython 
    - babel >=2.7.0

test:
  imports:
    - mkdocs_git_revision_date_localized_plugin
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
  summary: MkDocs plugin that enables displaying the date of the last git modification of a page.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpcloud
